/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { EthPriceFeed } from "../EthPriceFeed";

export class EthPriceFeed__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<EthPriceFeed> {
    return super.deploy(overrides || {}) as Promise<EthPriceFeed>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): EthPriceFeed {
    return super.attach(address) as EthPriceFeed;
  }
  connect(signer: Signer): EthPriceFeed__factory {
    return super.connect(signer) as EthPriceFeed__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EthPriceFeed {
    return new Contract(address, _abi, signerOrProvider) as EthPriceFeed;
  }
}

const _abi = [
  {
    inputs: [],
    name: "ONE",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "decimals",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "latestAnswer",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x6080604052601260005534801561001557600080fd5b5060b9806100246000396000f3fe6080604052348015600f57600080fd5b5060043610603c5760003560e01c8063313ce56714604157806350d25bcd146059578063c2ee3a0814605f575b600080fd5b60476065565b60408051918252519081900360200190f35b6047606b565b60476077565b60005481565b670de0b6b3a764000090565b670de0b6b3a76400008156fea2646970667358221220260b6285bd275fc53233c685dd566997049ec259b3b2d8e00f20e648c69d9f3164736f6c63430007040033";
