/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IBFactory } from "../IBFactory";

export class IBFactory__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBFactory {
    return new Contract(address, _abi, signerOrProvider) as IBFactory;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "pool",
        type: "address",
      },
    ],
    name: "LOG_NEW_POOL",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "b",
        type: "address",
      },
    ],
    name: "isBPool",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "newBPool",
    outputs: [
      {
        internalType: "contract IBPool",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_authorization",
        type: "address",
      },
    ],
    name: "setAuthorization",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "exchProxy",
        type: "address",
      },
    ],
    name: "setExchProxy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "operationsRegistry",
        type: "address",
      },
    ],
    name: "setOperationsRegistry",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "permissionManager",
        type: "address",
      },
    ],
    name: "setPermissionManager",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
