/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface BFactoryMockInterface extends ethers.utils.Interface {
  functions: {
    "isBPool(address)": FunctionFragment;
    "isBPoolAnswer()": FunctionFragment;
    "setIsBPoolAnswer(bool)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "isBPool", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isBPoolAnswer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setIsBPoolAnswer",
    values: [boolean]
  ): string;

  decodeFunctionResult(functionFragment: "isBPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isBPoolAnswer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setIsBPoolAnswer",
    data: BytesLike
  ): Result;

  events: {};
}

export class BFactoryMock extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: BFactoryMockInterface;

  functions: {
    isBPool(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    "isBPool(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isBPoolAnswer(overrides?: CallOverrides): Promise<[boolean]>;

    "isBPoolAnswer()"(overrides?: CallOverrides): Promise<[boolean]>;

    setIsBPoolAnswer(
      answer: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setIsBPoolAnswer(bool)"(
      answer: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  isBPool(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  "isBPool(address)"(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  isBPoolAnswer(overrides?: CallOverrides): Promise<boolean>;

  "isBPoolAnswer()"(overrides?: CallOverrides): Promise<boolean>;

  setIsBPoolAnswer(
    answer: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setIsBPoolAnswer(bool)"(
    answer: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    isBPool(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    "isBPool(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isBPoolAnswer(overrides?: CallOverrides): Promise<boolean>;

    "isBPoolAnswer()"(overrides?: CallOverrides): Promise<boolean>;

    setIsBPoolAnswer(answer: boolean, overrides?: CallOverrides): Promise<void>;

    "setIsBPoolAnswer(bool)"(
      answer: boolean,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    isBPool(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "isBPool(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isBPoolAnswer(overrides?: CallOverrides): Promise<BigNumber>;

    "isBPoolAnswer()"(overrides?: CallOverrides): Promise<BigNumber>;

    setIsBPoolAnswer(
      answer: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setIsBPoolAnswer(bool)"(
      answer: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    isBPool(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isBPool(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isBPoolAnswer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "isBPoolAnswer()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setIsBPoolAnswer(
      answer: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setIsBPoolAnswer(bool)"(
      answer: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
