/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface BPollProxyInterface extends ethers.utils.Interface {
  functions: {
    "batchSwapExactIn(tuple[],address,address,uint256,uint256)": FunctionFragment;
    "batchSwapExactOut(tuple[],address,address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "batchSwapExactIn",
    values: [
      {
        pool: string;
        tokenInParam: BigNumberish;
        tokenOutParam: BigNumberish;
        maxPrice: BigNumberish;
      }[],
      string,
      string,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "batchSwapExactOut",
    values: [
      {
        pool: string;
        tokenInParam: BigNumberish;
        tokenOutParam: BigNumberish;
        maxPrice: BigNumberish;
      }[],
      string,
      string,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchSwapExactIn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchSwapExactOut",
    data: BytesLike
  ): Result;

  events: {
    "LOG_CALL(bytes4,address,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LOG_CALL"): EventFragment;
}

export class BPollProxy extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: BPollProxyInterface;

  functions: {
    batchSwapExactIn(
      swaps: {
        pool: string;
        tokenInParam: BigNumberish;
        tokenOutParam: BigNumberish;
        maxPrice: BigNumberish;
      }[],
      tokenIn: string,
      tokenOut: string,
      totalAmountIn: BigNumberish,
      minTotalAmountOut: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "batchSwapExactIn(tuple[],address,address,uint256,uint256)"(
      swaps: {
        pool: string;
        tokenInParam: BigNumberish;
        tokenOutParam: BigNumberish;
        maxPrice: BigNumberish;
      }[],
      tokenIn: string,
      tokenOut: string,
      totalAmountIn: BigNumberish,
      minTotalAmountOut: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    batchSwapExactOut(
      swaps: {
        pool: string;
        tokenInParam: BigNumberish;
        tokenOutParam: BigNumberish;
        maxPrice: BigNumberish;
      }[],
      tokenIn: string,
      tokenOut: string,
      maxTotalAmountIn: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "batchSwapExactOut(tuple[],address,address,uint256)"(
      swaps: {
        pool: string;
        tokenInParam: BigNumberish;
        tokenOutParam: BigNumberish;
        maxPrice: BigNumberish;
      }[],
      tokenIn: string,
      tokenOut: string,
      maxTotalAmountIn: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  batchSwapExactIn(
    swaps: {
      pool: string;
      tokenInParam: BigNumberish;
      tokenOutParam: BigNumberish;
      maxPrice: BigNumberish;
    }[],
    tokenIn: string,
    tokenOut: string,
    totalAmountIn: BigNumberish,
    minTotalAmountOut: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "batchSwapExactIn(tuple[],address,address,uint256,uint256)"(
    swaps: {
      pool: string;
      tokenInParam: BigNumberish;
      tokenOutParam: BigNumberish;
      maxPrice: BigNumberish;
    }[],
    tokenIn: string,
    tokenOut: string,
    totalAmountIn: BigNumberish,
    minTotalAmountOut: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  batchSwapExactOut(
    swaps: {
      pool: string;
      tokenInParam: BigNumberish;
      tokenOutParam: BigNumberish;
      maxPrice: BigNumberish;
    }[],
    tokenIn: string,
    tokenOut: string,
    maxTotalAmountIn: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "batchSwapExactOut(tuple[],address,address,uint256)"(
    swaps: {
      pool: string;
      tokenInParam: BigNumberish;
      tokenOutParam: BigNumberish;
      maxPrice: BigNumberish;
    }[],
    tokenIn: string,
    tokenOut: string,
    maxTotalAmountIn: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    batchSwapExactIn(
      swaps: {
        pool: string;
        tokenInParam: BigNumberish;
        tokenOutParam: BigNumberish;
        maxPrice: BigNumberish;
      }[],
      tokenIn: string,
      tokenOut: string,
      totalAmountIn: BigNumberish,
      minTotalAmountOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "batchSwapExactIn(tuple[],address,address,uint256,uint256)"(
      swaps: {
        pool: string;
        tokenInParam: BigNumberish;
        tokenOutParam: BigNumberish;
        maxPrice: BigNumberish;
      }[],
      tokenIn: string,
      tokenOut: string,
      totalAmountIn: BigNumberish,
      minTotalAmountOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    batchSwapExactOut(
      swaps: {
        pool: string;
        tokenInParam: BigNumberish;
        tokenOutParam: BigNumberish;
        maxPrice: BigNumberish;
      }[],
      tokenIn: string,
      tokenOut: string,
      maxTotalAmountIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "batchSwapExactOut(tuple[],address,address,uint256)"(
      swaps: {
        pool: string;
        tokenInParam: BigNumberish;
        tokenOutParam: BigNumberish;
        maxPrice: BigNumberish;
      }[],
      tokenIn: string,
      tokenOut: string,
      maxTotalAmountIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    LOG_CALL(
      sig: BytesLike | null,
      caller: string | null,
      data: null
    ): EventFilter;
  };

  estimateGas: {
    batchSwapExactIn(
      swaps: {
        pool: string;
        tokenInParam: BigNumberish;
        tokenOutParam: BigNumberish;
        maxPrice: BigNumberish;
      }[],
      tokenIn: string,
      tokenOut: string,
      totalAmountIn: BigNumberish,
      minTotalAmountOut: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "batchSwapExactIn(tuple[],address,address,uint256,uint256)"(
      swaps: {
        pool: string;
        tokenInParam: BigNumberish;
        tokenOutParam: BigNumberish;
        maxPrice: BigNumberish;
      }[],
      tokenIn: string,
      tokenOut: string,
      totalAmountIn: BigNumberish,
      minTotalAmountOut: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    batchSwapExactOut(
      swaps: {
        pool: string;
        tokenInParam: BigNumberish;
        tokenOutParam: BigNumberish;
        maxPrice: BigNumberish;
      }[],
      tokenIn: string,
      tokenOut: string,
      maxTotalAmountIn: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "batchSwapExactOut(tuple[],address,address,uint256)"(
      swaps: {
        pool: string;
        tokenInParam: BigNumberish;
        tokenOutParam: BigNumberish;
        maxPrice: BigNumberish;
      }[],
      tokenIn: string,
      tokenOut: string,
      maxTotalAmountIn: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    batchSwapExactIn(
      swaps: {
        pool: string;
        tokenInParam: BigNumberish;
        tokenOutParam: BigNumberish;
        maxPrice: BigNumberish;
      }[],
      tokenIn: string,
      tokenOut: string,
      totalAmountIn: BigNumberish,
      minTotalAmountOut: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "batchSwapExactIn(tuple[],address,address,uint256,uint256)"(
      swaps: {
        pool: string;
        tokenInParam: BigNumberish;
        tokenOutParam: BigNumberish;
        maxPrice: BigNumberish;
      }[],
      tokenIn: string,
      tokenOut: string,
      totalAmountIn: BigNumberish,
      minTotalAmountOut: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    batchSwapExactOut(
      swaps: {
        pool: string;
        tokenInParam: BigNumberish;
        tokenOutParam: BigNumberish;
        maxPrice: BigNumberish;
      }[],
      tokenIn: string,
      tokenOut: string,
      maxTotalAmountIn: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "batchSwapExactOut(tuple[],address,address,uint256)"(
      swaps: {
        pool: string;
        tokenInParam: BigNumberish;
        tokenOutParam: BigNumberish;
        maxPrice: BigNumberish;
      }[],
      tokenIn: string,
      tokenOut: string,
      maxTotalAmountIn: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
