/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IBFactoryInterface extends ethers.utils.Interface {
  functions: {
    "isBPool(address)": FunctionFragment;
    "newBPool()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "isBPool", values: [string]): string;
  encodeFunctionData(functionFragment: "newBPool", values?: undefined): string;

  decodeFunctionResult(functionFragment: "isBPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "newBPool", data: BytesLike): Result;

  events: {};
}

export class IBFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IBFactoryInterface;

  functions: {
    isBPool(b: string, overrides?: CallOverrides): Promise<[boolean]>;

    "isBPool(address)"(
      b: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    newBPool(overrides?: Overrides): Promise<ContractTransaction>;

    "newBPool()"(overrides?: Overrides): Promise<ContractTransaction>;
  };

  isBPool(b: string, overrides?: CallOverrides): Promise<boolean>;

  "isBPool(address)"(b: string, overrides?: CallOverrides): Promise<boolean>;

  newBPool(overrides?: Overrides): Promise<ContractTransaction>;

  "newBPool()"(overrides?: Overrides): Promise<ContractTransaction>;

  callStatic: {
    isBPool(b: string, overrides?: CallOverrides): Promise<boolean>;

    "isBPool(address)"(b: string, overrides?: CallOverrides): Promise<boolean>;

    newBPool(overrides?: CallOverrides): Promise<string>;

    "newBPool()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    isBPool(b: string, overrides?: CallOverrides): Promise<BigNumber>;

    "isBPool(address)"(
      b: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    newBPool(overrides?: Overrides): Promise<BigNumber>;

    "newBPool()"(overrides?: Overrides): Promise<BigNumber>;
  };

  populateTransaction: {
    isBPool(
      b: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isBPool(address)"(
      b: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    newBPool(overrides?: Overrides): Promise<PopulatedTransaction>;

    "newBPool()"(overrides?: Overrides): Promise<PopulatedTransaction>;
  };
}
