/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IEurPriceFeedInterface extends ethers.utils.Interface {
  functions: {
    "getPrice(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "getPrice", values: [string]): string;

  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;

  events: {};
}

export class IEurPriceFeed extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IEurPriceFeedInterface;

  functions: {
    getPrice(
      _asset: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "getPrice(address)"(
      _asset: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  getPrice(_asset: string, overrides?: Overrides): Promise<ContractTransaction>;

  "getPrice(address)"(
    _asset: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    getPrice(_asset: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getPrice(address)"(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getPrice(_asset: string, overrides?: Overrides): Promise<BigNumber>;

    "getPrice(address)"(
      _asset: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getPrice(
      _asset: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "getPrice(address)"(
      _asset: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
