/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface PermissionManagerInterface extends ethers.utils.Interface {
  functions: {
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "PERMISSIONS_ADMIN_ROLE()": FunctionFragment;
    "PROTOCOL_CONTRACT()": FunctionFragment;
    "REJECTED_ID()": FunctionFragment;
    "SUSPENDED_ID()": FunctionFragment;
    "TIER_1_ID()": FunctionFragment;
    "TIER_2_ID()": FunctionFragment;
    "assignItem(uint256,address[])": FunctionFragment;
    "assingTier1(address[])": FunctionFragment;
    "assingTier2(tuple[])": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "getRoleMember(bytes32,uint256)": FunctionFragment;
    "getRoleMemberCount(bytes32)": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "hasTier1(address)": FunctionFragment;
    "hasTier2(address)": FunctionFragment;
    "initialize(address,address)": FunctionFragment;
    "isRejected(address)": FunctionFragment;
    "isSuspended(address)": FunctionFragment;
    "permissionItems()": FunctionFragment;
    "rejectUser(tuple[])": FunctionFragment;
    "removeItem(uint256,address[])": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "revokeTier1(address[])": FunctionFragment;
    "revokeTier2(tuple[])": FunctionFragment;
    "setPermissionItems(address)": FunctionFragment;
    "setPermissionsAdmin(address)": FunctionFragment;
    "suspendUser(tuple[])": FunctionFragment;
    "unrejectUser(tuple[])": FunctionFragment;
    "unsuspendUser(tuple[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PERMISSIONS_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROTOCOL_CONTRACT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REJECTED_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SUSPENDED_ID",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "TIER_1_ID", values?: undefined): string;
  encodeFunctionData(functionFragment: "TIER_2_ID", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "assignItem",
    values: [BigNumberish, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "assingTier1",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "assingTier2",
    values: [{ user: string; proxy: string }[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleMember",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleMemberCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(functionFragment: "hasTier1", values: [string]): string;
  encodeFunctionData(functionFragment: "hasTier2", values: [string]): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "isRejected", values: [string]): string;
  encodeFunctionData(functionFragment: "isSuspended", values: [string]): string;
  encodeFunctionData(
    functionFragment: "permissionItems",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rejectUser",
    values: [{ user: string; proxy: string }[]]
  ): string;
  encodeFunctionData(
    functionFragment: "removeItem",
    values: [BigNumberish, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeTier1",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeTier2",
    values: [{ user: string; proxy: string }[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setPermissionItems",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setPermissionsAdmin",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "suspendUser",
    values: [{ user: string; proxy: string }[]]
  ): string;
  encodeFunctionData(
    functionFragment: "unrejectUser",
    values: [{ user: string; proxy: string }[]]
  ): string;
  encodeFunctionData(
    functionFragment: "unsuspendUser",
    values: [{ user: string; proxy: string }[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PERMISSIONS_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROTOCOL_CONTRACT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REJECTED_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SUSPENDED_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "TIER_1_ID", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "TIER_2_ID", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "assignItem", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "assingTier1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assingTier2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleMemberCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasTier1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasTier2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isRejected", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isSuspended",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "permissionItems",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rejectUser", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "removeItem", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeTier1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeTier2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPermissionItems",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPermissionsAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "suspendUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unrejectUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unsuspendUser",
    data: BytesLike
  ): Result;

  events: {
    "PermissionItemsSet(address)": EventFragment;
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "PermissionItemsSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
}

export class PermissionManager extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: PermissionManagerInterface;

  functions: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    "DEFAULT_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<[string]>;

    PERMISSIONS_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    "PERMISSIONS_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<[string]>;

    PROTOCOL_CONTRACT(overrides?: CallOverrides): Promise<[BigNumber]>;

    "PROTOCOL_CONTRACT()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    REJECTED_ID(overrides?: CallOverrides): Promise<[BigNumber]>;

    "REJECTED_ID()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    SUSPENDED_ID(overrides?: CallOverrides): Promise<[BigNumber]>;

    "SUSPENDED_ID()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    TIER_1_ID(overrides?: CallOverrides): Promise<[BigNumber]>;

    "TIER_1_ID()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    TIER_2_ID(overrides?: CallOverrides): Promise<[BigNumber]>;

    "TIER_2_ID()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    assignItem(
      _itemId: BigNumberish,
      _accounts: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "assignItem(uint256,address[])"(
      _itemId: BigNumberish,
      _accounts: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    assingTier1(
      _accounts: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "assingTier1(address[])"(
      _accounts: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    assingTier2(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "assingTier2(tuple[])"(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    "getRoleAdmin(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getRoleMember(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "getRoleMember(bytes32,uint256)"(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getRoleMemberCount(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getRoleMemberCount(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "grantRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "hasRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    hasTier1(_account: string, overrides?: CallOverrides): Promise<[boolean]>;

    "hasTier1(address)"(
      _account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    hasTier2(_account: string, overrides?: CallOverrides): Promise<[boolean]>;

    "hasTier2(address)"(
      _account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    initialize(
      _permissionItems: string,
      _admin: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize(address,address)"(
      _permissionItems: string,
      _admin: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    isRejected(_account: string, overrides?: CallOverrides): Promise<[boolean]>;

    "isRejected(address)"(
      _account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isSuspended(
      _account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "isSuspended(address)"(
      _account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    permissionItems(overrides?: CallOverrides): Promise<[string]>;

    "permissionItems()"(overrides?: CallOverrides): Promise<[string]>;

    rejectUser(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "rejectUser(tuple[])"(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    removeItem(
      _itemId: BigNumberish,
      _accounts: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "removeItem(uint256,address[])"(
      _itemId: BigNumberish,
      _accounts: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "renounceRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "revokeRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    revokeTier1(
      _accounts: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "revokeTier1(address[])"(
      _accounts: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    revokeTier2(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "revokeTier2(tuple[])"(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setPermissionItems(
      _permissionItems: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setPermissionItems(address)"(
      _permissionItems: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setPermissionsAdmin(
      _permissionsAdmin: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setPermissionsAdmin(address)"(
      _permissionsAdmin: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    suspendUser(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "suspendUser(tuple[])"(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    unrejectUser(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "unrejectUser(tuple[])"(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    unsuspendUser(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "unsuspendUser(tuple[])"(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  "DEFAULT_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<string>;

  PERMISSIONS_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  "PERMISSIONS_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<string>;

  PROTOCOL_CONTRACT(overrides?: CallOverrides): Promise<BigNumber>;

  "PROTOCOL_CONTRACT()"(overrides?: CallOverrides): Promise<BigNumber>;

  REJECTED_ID(overrides?: CallOverrides): Promise<BigNumber>;

  "REJECTED_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

  SUSPENDED_ID(overrides?: CallOverrides): Promise<BigNumber>;

  "SUSPENDED_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

  TIER_1_ID(overrides?: CallOverrides): Promise<BigNumber>;

  "TIER_1_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

  TIER_2_ID(overrides?: CallOverrides): Promise<BigNumber>;

  "TIER_2_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

  assignItem(
    _itemId: BigNumberish,
    _accounts: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "assignItem(uint256,address[])"(
    _itemId: BigNumberish,
    _accounts: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  assingTier1(
    _accounts: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "assingTier1(address[])"(
    _accounts: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  assingTier2(
    _usersProxies: { user: string; proxy: string }[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "assingTier2(tuple[])"(
    _usersProxies: { user: string; proxy: string }[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

  "getRoleAdmin(bytes32)"(
    role: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  getRoleMember(
    role: BytesLike,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getRoleMember(bytes32,uint256)"(
    role: BytesLike,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getRoleMemberCount(
    role: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getRoleMemberCount(bytes32)"(
    role: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  grantRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "grantRole(bytes32,address)"(
    role: BytesLike,
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  hasRole(
    role: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "hasRole(bytes32,address)"(
    role: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  hasTier1(_account: string, overrides?: CallOverrides): Promise<boolean>;

  "hasTier1(address)"(
    _account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  hasTier2(_account: string, overrides?: CallOverrides): Promise<boolean>;

  "hasTier2(address)"(
    _account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  initialize(
    _permissionItems: string,
    _admin: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize(address,address)"(
    _permissionItems: string,
    _admin: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  isRejected(_account: string, overrides?: CallOverrides): Promise<boolean>;

  "isRejected(address)"(
    _account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isSuspended(_account: string, overrides?: CallOverrides): Promise<boolean>;

  "isSuspended(address)"(
    _account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  permissionItems(overrides?: CallOverrides): Promise<string>;

  "permissionItems()"(overrides?: CallOverrides): Promise<string>;

  rejectUser(
    _usersProxies: { user: string; proxy: string }[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "rejectUser(tuple[])"(
    _usersProxies: { user: string; proxy: string }[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  removeItem(
    _itemId: BigNumberish,
    _accounts: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "removeItem(uint256,address[])"(
    _itemId: BigNumberish,
    _accounts: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  renounceRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "renounceRole(bytes32,address)"(
    role: BytesLike,
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  revokeRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "revokeRole(bytes32,address)"(
    role: BytesLike,
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  revokeTier1(
    _accounts: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "revokeTier1(address[])"(
    _accounts: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  revokeTier2(
    _usersProxies: { user: string; proxy: string }[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "revokeTier2(tuple[])"(
    _usersProxies: { user: string; proxy: string }[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setPermissionItems(
    _permissionItems: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setPermissionItems(address)"(
    _permissionItems: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setPermissionsAdmin(
    _permissionsAdmin: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setPermissionsAdmin(address)"(
    _permissionsAdmin: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  suspendUser(
    _usersProxies: { user: string; proxy: string }[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "suspendUser(tuple[])"(
    _usersProxies: { user: string; proxy: string }[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  unrejectUser(
    _usersProxies: { user: string; proxy: string }[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "unrejectUser(tuple[])"(
    _usersProxies: { user: string; proxy: string }[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  unsuspendUser(
    _usersProxies: { user: string; proxy: string }[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "unsuspendUser(tuple[])"(
    _usersProxies: { user: string; proxy: string }[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    "DEFAULT_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<string>;

    PERMISSIONS_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    "PERMISSIONS_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<string>;

    PROTOCOL_CONTRACT(overrides?: CallOverrides): Promise<BigNumber>;

    "PROTOCOL_CONTRACT()"(overrides?: CallOverrides): Promise<BigNumber>;

    REJECTED_ID(overrides?: CallOverrides): Promise<BigNumber>;

    "REJECTED_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

    SUSPENDED_ID(overrides?: CallOverrides): Promise<BigNumber>;

    "SUSPENDED_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

    TIER_1_ID(overrides?: CallOverrides): Promise<BigNumber>;

    "TIER_1_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

    TIER_2_ID(overrides?: CallOverrides): Promise<BigNumber>;

    "TIER_2_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

    assignItem(
      _itemId: BigNumberish,
      _accounts: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    "assignItem(uint256,address[])"(
      _itemId: BigNumberish,
      _accounts: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    assingTier1(_accounts: string[], overrides?: CallOverrides): Promise<void>;

    "assingTier1(address[])"(
      _accounts: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    assingTier2(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: CallOverrides
    ): Promise<void>;

    "assingTier2(tuple[])"(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: CallOverrides
    ): Promise<void>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

    "getRoleAdmin(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getRoleMember(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getRoleMember(bytes32,uint256)"(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getRoleMemberCount(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getRoleMemberCount(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "grantRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "hasRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    hasTier1(_account: string, overrides?: CallOverrides): Promise<boolean>;

    "hasTier1(address)"(
      _account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    hasTier2(_account: string, overrides?: CallOverrides): Promise<boolean>;

    "hasTier2(address)"(
      _account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    initialize(
      _permissionItems: string,
      _admin: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(address,address)"(
      _permissionItems: string,
      _admin: string,
      overrides?: CallOverrides
    ): Promise<void>;

    isRejected(_account: string, overrides?: CallOverrides): Promise<boolean>;

    "isRejected(address)"(
      _account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isSuspended(_account: string, overrides?: CallOverrides): Promise<boolean>;

    "isSuspended(address)"(
      _account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    permissionItems(overrides?: CallOverrides): Promise<string>;

    "permissionItems()"(overrides?: CallOverrides): Promise<string>;

    rejectUser(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: CallOverrides
    ): Promise<void>;

    "rejectUser(tuple[])"(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: CallOverrides
    ): Promise<void>;

    removeItem(
      _itemId: BigNumberish,
      _accounts: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    "removeItem(uint256,address[])"(
      _itemId: BigNumberish,
      _accounts: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "renounceRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "revokeRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeTier1(_accounts: string[], overrides?: CallOverrides): Promise<void>;

    "revokeTier1(address[])"(
      _accounts: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    revokeTier2(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: CallOverrides
    ): Promise<void>;

    "revokeTier2(tuple[])"(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: CallOverrides
    ): Promise<void>;

    setPermissionItems(
      _permissionItems: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "setPermissionItems(address)"(
      _permissionItems: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setPermissionsAdmin(
      _permissionsAdmin: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setPermissionsAdmin(address)"(
      _permissionsAdmin: string,
      overrides?: CallOverrides
    ): Promise<void>;

    suspendUser(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: CallOverrides
    ): Promise<void>;

    "suspendUser(tuple[])"(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: CallOverrides
    ): Promise<void>;

    unrejectUser(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: CallOverrides
    ): Promise<void>;

    "unrejectUser(tuple[])"(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: CallOverrides
    ): Promise<void>;

    unsuspendUser(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: CallOverrides
    ): Promise<void>;

    "unsuspendUser(tuple[])"(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    PermissionItemsSet(newPermissions: string | null): EventFilter;

    RoleAdminChanged(
      role: BytesLike | null,
      previousAdminRole: BytesLike | null,
      newAdminRole: BytesLike | null
    ): EventFilter;

    RoleGranted(
      role: BytesLike | null,
      account: string | null,
      sender: string | null
    ): EventFilter;

    RoleRevoked(
      role: BytesLike | null,
      account: string | null,
      sender: string | null
    ): EventFilter;
  };

  estimateGas: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    "DEFAULT_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<BigNumber>;

    PERMISSIONS_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    "PERMISSIONS_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<BigNumber>;

    PROTOCOL_CONTRACT(overrides?: CallOverrides): Promise<BigNumber>;

    "PROTOCOL_CONTRACT()"(overrides?: CallOverrides): Promise<BigNumber>;

    REJECTED_ID(overrides?: CallOverrides): Promise<BigNumber>;

    "REJECTED_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

    SUSPENDED_ID(overrides?: CallOverrides): Promise<BigNumber>;

    "SUSPENDED_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

    TIER_1_ID(overrides?: CallOverrides): Promise<BigNumber>;

    "TIER_1_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

    TIER_2_ID(overrides?: CallOverrides): Promise<BigNumber>;

    "TIER_2_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

    assignItem(
      _itemId: BigNumberish,
      _accounts: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "assignItem(uint256,address[])"(
      _itemId: BigNumberish,
      _accounts: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    assingTier1(_accounts: string[], overrides?: Overrides): Promise<BigNumber>;

    "assingTier1(address[])"(
      _accounts: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    assingTier2(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "assingTier2(tuple[])"(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getRoleAdmin(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleMember(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getRoleMember(bytes32,uint256)"(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleMemberCount(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getRoleMemberCount(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "grantRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "hasRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hasTier1(_account: string, overrides?: CallOverrides): Promise<BigNumber>;

    "hasTier1(address)"(
      _account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hasTier2(_account: string, overrides?: CallOverrides): Promise<BigNumber>;

    "hasTier2(address)"(
      _account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      _permissionItems: string,
      _admin: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initialize(address,address)"(
      _permissionItems: string,
      _admin: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    isRejected(_account: string, overrides?: CallOverrides): Promise<BigNumber>;

    "isRejected(address)"(
      _account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isSuspended(
      _account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isSuspended(address)"(
      _account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    permissionItems(overrides?: CallOverrides): Promise<BigNumber>;

    "permissionItems()"(overrides?: CallOverrides): Promise<BigNumber>;

    rejectUser(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "rejectUser(tuple[])"(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    removeItem(
      _itemId: BigNumberish,
      _accounts: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "removeItem(uint256,address[])"(
      _itemId: BigNumberish,
      _accounts: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "renounceRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "revokeRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    revokeTier1(_accounts: string[], overrides?: Overrides): Promise<BigNumber>;

    "revokeTier1(address[])"(
      _accounts: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    revokeTier2(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "revokeTier2(tuple[])"(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    setPermissionItems(
      _permissionItems: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setPermissionItems(address)"(
      _permissionItems: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setPermissionsAdmin(
      _permissionsAdmin: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setPermissionsAdmin(address)"(
      _permissionsAdmin: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    suspendUser(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "suspendUser(tuple[])"(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    unrejectUser(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "unrejectUser(tuple[])"(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    unsuspendUser(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "unsuspendUser(tuple[])"(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "DEFAULT_ADMIN_ROLE()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    PERMISSIONS_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "PERMISSIONS_ADMIN_ROLE()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    PROTOCOL_CONTRACT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "PROTOCOL_CONTRACT()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    REJECTED_ID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "REJECTED_ID()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    SUSPENDED_ID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "SUSPENDED_ID()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    TIER_1_ID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "TIER_1_ID()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    TIER_2_ID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "TIER_2_ID()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    assignItem(
      _itemId: BigNumberish,
      _accounts: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "assignItem(uint256,address[])"(
      _itemId: BigNumberish,
      _accounts: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    assingTier1(
      _accounts: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "assingTier1(address[])"(
      _accounts: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    assingTier2(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "assingTier2(tuple[])"(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getRoleAdmin(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleMember(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getRoleMember(bytes32,uint256)"(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleMemberCount(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getRoleMemberCount(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "grantRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "hasRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasTier1(
      _account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "hasTier1(address)"(
      _account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasTier2(
      _account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "hasTier2(address)"(
      _account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _permissionItems: string,
      _admin: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize(address,address)"(
      _permissionItems: string,
      _admin: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    isRejected(
      _account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isRejected(address)"(
      _account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isSuspended(
      _account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isSuspended(address)"(
      _account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    permissionItems(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "permissionItems()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rejectUser(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "rejectUser(tuple[])"(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    removeItem(
      _itemId: BigNumberish,
      _accounts: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "removeItem(uint256,address[])"(
      _itemId: BigNumberish,
      _accounts: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "renounceRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "revokeRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    revokeTier1(
      _accounts: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "revokeTier1(address[])"(
      _accounts: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    revokeTier2(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "revokeTier2(tuple[])"(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setPermissionItems(
      _permissionItems: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setPermissionItems(address)"(
      _permissionItems: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setPermissionsAdmin(
      _permissionsAdmin: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setPermissionsAdmin(address)"(
      _permissionsAdmin: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    suspendUser(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "suspendUser(tuple[])"(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    unrejectUser(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "unrejectUser(tuple[])"(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    unsuspendUser(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "unsuspendUser(tuple[])"(
      _usersProxies: { user: string; proxy: string }[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
